Repository Northeastern-Electric-Racing/PM-Dashboard-v2, pull requests merged in 2021-02, with the labels that each got.

#45 Set up ESLint and Prettier
  Docs/Onboarding.md
  package-lock.json
  package.json
  src/backend/functions/example.ts
  src/backend/functions/seed.ts
  src/backend/functions/users.ts
  src/backend/prisma/schema.prisma
  src/backend/tests/seed.test.ts
  src/index.css
Labels: documentation

#46 Mark lint and format as implemented
  README.md
Labels: documentation

#49 #20-mark react-google-charts as researched and decided
  README.md
Labels: front-end

#51 #37-adding database design row and removing issue column from readme
  README.md
Labels: documentation

#52 Setup front end folders
  README.md
  docs/About.md
  docs/ContributorGuide.md
  docs/CreateReactApp.md
  docs/Deployment.md
  docs/Onboarding.md
  docs/ProductManagement.md
  src/App.tsx
  src/components/change-request-details/change-request-details.module.css
  src/components/change-request-details/change-request-details.test.tsx
  src/components/change-request-details/change-request-details.tsx
  src/components/project-details/project-details.module.css
  src/components/project-details/project-details.test.tsx
  src/components/project-details/project-details.tsx
  src/containers/change-requests-table/change-requests-table.module.css
  src/containers/change-requests-table/change-requests-table.test.tsx
  src/containers/change-requests-table/change-requests-table.tsx
  src/containers/projects-table/projects-table.module.css
  src/containers/projects-table/projects-table.test.tsx
  src/containers/projects-table/projects-table.tsx
  src/pages/change-requests/change-requests.module.css
  src/pages/change-requests/change-requests.test.tsx
  src/pages/change-requests/change-requests.tsx
  src/pages/projects/projects.module.css
  src/pages/projects/projects.test.tsx
  src/pages/projects/projects.tsx
  src/types/change-request-types.ts
  src/types/project-types.ts
Labels: front-end

#65 Added per-file license statements
  docs/Onboarding.md
  src/App.css
  src/App.test.tsx
  src/App.tsx
  src/backend/functions/example.ts
  src/backend/functions/seed.ts
  src/backend/functions/users.ts
  src/backend/tests/seed.test.ts
  src/components/change-request-details/change-request-details.module.css
  src/components/change-request-details/change-request-details.test.tsx
  src/components/change-request-details/change-request-details.tsx
  src/components/project-details/project-details.module.css
  src/components/project-details/project-details.test.tsx
  src/components/project-details/project-details.tsx
  src/containers/change-requests-table/change-requests-table.module.css
  src/containers/change-requests-table/change-requests-table.test.tsx
  src/containers/change-requests-table/change-requests-table.tsx
  src/containers/projects-table/projects-table.module.css
  src/containers/projects-table/projects-table.test.tsx
  src/containers/projects-table/projects-table.tsx
  src/index.css
  src/index.tsx
  src/pages/change-requests/change-requests.module.css
  src/pages/change-requests/change-requests.test.tsx
  src/pages/change-requests/change-requests.tsx
  src/pages/projects/projects.module.css
  src/pages/projects/projects.test.tsx
  src/pages/projects/projects.tsx
  src/setupProxy.js
  src/types/change-request-types.ts
  src/types/project-types.ts
Labels: documentation

#63 Create LICENSE
  LICENSE
Labels: documentation

#74 Projects endpoint & table
  README.md
  docs/Onboarding.md
  package-lock.json
  package.json
  src/App.test.tsx
  src/App.tsx
  src/backend/functions/projects.ts
  src/backend/tests/projects.test.ts
  src/components/project-details/project-details.test.tsx
  src/containers/projects-table/projects-table.module.css
  src/containers/projects-table/projects-table.test.tsx
  src/containers/projects-table/projects-table.tsx
  src/index.tsx
  src/shared/axios.ts
  src/types/project-types.ts
Labels: back-end, front-end, new feature

#81 Assembling A Utils Folder for Code Shared In Backend
  package-lock.json
  package.json
  src/backend/functions/example.ts
  src/backend/functions/seed.ts
  src/components/change-request-details/change-request-details.test.tsx
  src/components/change-request-details/change-request-details.tsx
  src/components/project-details/project-details.test.tsx
  src/components/project-details/project-details.tsx
  src/containers/projects-table/projects-table.test.tsx
  src/containers/projects-table/projects-table.tsx
  src/utils/.gitignore
  src/utils/package-lock.json
  src/utils/package.json
  src/utils/src/example-shared.ts
  src/utils/src/index.ts
  src/utils/src/types/change-request-types.ts
  src/utils/src/types/project-types.ts
  src/utils/tests/example-shared.test.ts
  src/utils/tsconfig.json
Labels: back-end

#82 Decided on URL Routing
  README.md
Labels: documentation

#84 Implemented Simple React Router
  README.md
  package-lock.json
  package.json
  public/_redirects
  src/App.css
  src/App.test.tsx
  src/App.tsx
Labels: front-end

#85 Updated Packaged.json
  package.json
  src/backend/functions/example.ts
Labels: documentation

#86 Add license snippets
  src/backend/functions/projects.ts
  src/backend/prisma/schema.prisma
  src/backend/tests/projects.test.ts
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/shared/axios.ts
Labels: documentation

#87 Updated docs
  README.md
  docs/About.md
  docs/ContributorGuide.md
Labels: documentation
