Repository Northeastern-Electric-Racing/PM-Dashboard-v2, pull requests merged in 2021-01, with the labels that each got.

#13 Docs - Improving Readme
  README.md
Labels: documentation

#15 Docs - Add Project Setup Checklist
  README.md
Labels: documentation

#31 #16-adding researched and decided flags to readme for react testing library
  README.md
Labels: documentation

#35 #23-Adding AWS info as database provider to readme
  README.md
Labels: back-end

#36 Split and Reorganize the README
  Docs/About.md
  Docs/ContributorGuide.md
  Docs/Deployment.md
  Docs/Onboarding.md
  README.md
Labels: documentation

#39 Decided on Prisma for ORM
  README.md
Labels: back-end, documentation

#41 Set up prisma & local PostgreSQL
  .gitignore
  Docs/Onboarding.md
  README.md
  package-lock.json
  package.json
  prisma/migrations/20210130094615_init/migration.sql
  prisma/migrations/20210130095228_add_user_age/migration.sql
  prisma/migrations/migration_lock.toml
  prisma/schema.prisma
  src/lambda/seed.ts
  src/lambda/users.ts
Labels: back-end, documentation

#43 Testing backend functions
  package.json
  src/backend/functions/example.ts
  src/backend/functions/seed.ts
  src/backend/functions/users.ts
  src/backend/prisma/migrations/20210130094615_init/migration.sql
  src/backend/prisma/migrations/20210130095228_add_user_age/migration.sql
  src/backend/prisma/migrations/migration_lock.toml
  src/backend/prisma/schema.prisma
  src/backend/tests/seed.test.ts
  tsconfig.json
Labels: back-end
