Repository Northeastern-Electric-Racing/PM-Dashboard-v2, pull requests merged in 2021-05, with the labels that each got.

#175 Major changes to Prisma schema and application types
  src/backend/functions/projects.ts
  src/backend/prisma/migrations/20210130094615_init/migration.sql
  src/backend/prisma/migrations/20210130095228_add_user_age/migration.sql
  src/backend/prisma/migrations/20210419064854_major_updates/migration.sql
  src/backend/prisma/migrations/20210429224026_init/migration.sql
  src/backend/prisma/migrations/20210430171521_sync_with_types/migration.sql
  src/backend/prisma/schema.prisma
  src/backend/prisma/seed.ts
  src/components/change-request-details/change-request-details.test.tsx
  src/components/change-request-details/change-request-details.tsx
  src/components/project-details/project-details.test.tsx
  src/components/project-details/project-details.tsx
  src/shared/pipes.tsx
  src/utils/src/dummy-data.ts
  src/utils/src/index.ts
  src/utils/src/types/change-request-types.ts
  src/utils/src/types/implemented-change-types.ts
  src/utils/src/types/project-types.ts
  src/utils/src/types/wbs-types.ts
Labels: back-end, improvement

#177 Fixing all the tests
  src/backend/functions/change-requests.ts
  src/backend/functions/projects.ts
  src/backend/functions/users.ts
  src/backend/tests/change-requests.test.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/users.test.ts
  src/backend/tests/work-packages.test.ts
  src/utils/src/api-utils.ts
Labels: back-end, bug

#179 Remove unused imports
  src/components/change-request-details/change-request-details.tsx
Labels: bug, front-end

#184 Update API types and add factory functions
  package-lock.json
  package.json
  src/backend/functions/change-requests.ts
  src/backend/functions/projects.ts
  src/backend/functions/users.ts
  src/backend/functions/work-packages.ts
  src/backend/tests/change-requests.test.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/users.test.ts
  src/utils/package-lock.json
  src/utils/package.json
  src/utils/src/api-utils.ts
  src/utils/src/dummy-data.ts
  src/utils/src/types/api-utils-types.ts
  src/utils/tests/api-utils.test.ts
Labels: back-end, enhancement, new feature

#188 Expanded work package API endpoint with single work package lookup
  src/backend/functions/work-packages.ts
  src/backend/tests/work-packages.test.ts
Labels: back-end, new feature

#186 Create data for seeding database
  src/backend/prisma/migrations/20210430171521_sync_with_types/migration.sql
  src/backend/prisma/migrations/20210504070051_init/migration.sql
  src/backend/prisma/schema.prisma
  src/backend/prisma/seed-data/change-requests.ts
  src/backend/prisma/seed-data/projects.ts
  src/backend/prisma/seed-data/users.ts
  src/backend/prisma/seed-data/work-packages.ts
  src/backend/prisma/seed.ts
Labels: back-end, enhancement

#190 #160 - Created the work package changes component
  src/app/app-authenticated/app-authenticated.tsx
  src/components/work-package-changes/work-package-changes.module.css
  src/components/work-package-changes/work-package-changes.test.tsx
  src/components/work-package-changes/work-package-changes.tsx
  src/utils/src/dummy-data.ts
  src/utils/src/types/project-types.ts
Labels: front-end, new feature

#197 #156 - created the description list component
  src/components/description-list/description-list.module.css
  src/components/description-list/description-list.test.tsx
  src/components/description-list/description-list.tsx
Labels: front-end, new feature

#105 #73 added project-details component
  src/components/project-details/project-details.module.css
  src/components/project-details/project-details.test.tsx
  src/components/project-details/project-details.tsx
  src/index.css
  src/pages/wbs-details/wbs-details.tsx
  src/shared/pipes.tsx
Labels: front-end, new feature

#209 #139 - Fixed image and link styling
  public/NER-Logo-App-Icon.png
  public/manifest.json
  src/components/nav-top-bar/nav-top-bar.module.css
  src/components/nav-top-bar/nav-top-bar.tsx
Labels: bug, front-end

#218 Clean up linting errors
  src/app/app-main/app-main.tsx
  src/components/description-list/description-list.tsx
  src/components/work-package-changes/work-package-changes.module.css
  src/components/work-package-changes/work-package-changes.test.tsx
  src/components/work-package-changes/work-package-changes.tsx
Labels: front-end, improvement

#217 Create test support folder
  src/app/app-authenticated/app-authenticated.test.tsx
  src/app/app-main/app-main.test.tsx
  src/app/app-public/app-public.test.tsx
  src/components/change-request-details/change-request-details.test.tsx
  src/components/change-requests-table/change-requests-table.test.tsx
  src/components/description-list/description-list.test.tsx
  src/components/nav-notifications-menu/nav-notifications-menu.test.tsx
  src/components/nav-page-links/nav-page-links.test.tsx
  src/components/nav-top-bar/nav-top-bar.test.tsx
  src/components/nav-user-menu/nav-user-menu.test.tsx
  src/components/project-details/project-details.test.tsx
  src/components/work-package-changes/work-package-changes.test.tsx
  src/components/work-package-dependencies/work-package-dependencies.test.tsx
  src/components/work-package-details/work-package-details.test.tsx
  src/components/work-package-rules/work-package-rules.test.tsx
  src/components/work-package-summary/work-package-summary.test.tsx
  src/containers/change-requests-table/change-requests-table.test.tsx
  src/containers/projects-table/projects-table.test.tsx
  src/pages/change-request-details/change-request-details.test.tsx
  src/pages/change-requests/change-requests.test.tsx
  src/pages/login/login.test.tsx
  src/pages/projects/projects.test.tsx
  src/pages/wbs-details/wbs-details.test.tsx
  src/shared/tests/end-date-pipe.test.tsx
  src/shared/tests/list-pipe.test.tsx
  src/test-support/test-data/change-requests.stub.ts
  src/test-support/test-data/projects.stub.ts
  src/test-support/test-data/test-utils.stub.ts
  src/test-support/test-data/users.stub.ts
  src/test-support/test-data/wbs-numbers.stub.ts
  src/test-support/test-data/work-packages.stub.ts
  src/test-support/test-utils.tsx
Labels: front-end, improvement

#222 #129 remove function type
  src/app/app-authenticated/app-authenticated.test.tsx
  src/app/app-main/app-main.test.tsx
  src/app/app-public/app-public.test.tsx
  src/components/change-request-details/change-request-details.tsx
  src/components/nav-notifications-menu/nav-notifications-menu.test.tsx
  src/components/nav-page-links/nav-page-links.test.tsx
  src/components/nav-top-bar/nav-top-bar.test.tsx
  src/components/nav-user-menu/nav-user-menu.test.tsx
  src/containers/change-requests-table/change-requests-table.tsx
  src/containers/projects-table/projects-table.tsx
  src/pages/change-request-details/change-request-details.test.tsx
  src/pages/change-request-details/change-request-details.tsx
  src/pages/change-requests/change-requests.test.tsx
  src/pages/login/login.test.tsx
  src/pages/projects/projects.test.tsx
  src/pages/wbs-details/wbs-details.test.tsx
  src/shared/pipes.tsx
  src/utils/src/validate-wbs.ts
Labels: front-end, improvement

#210 implement front end services
  package-lock.json
  package.json
  src/components/work-package-rules/work-package-rules.tsx
  src/pages/change-request-details/change-request-details.test.tsx
  src/pages/change-request-details/change-request-details.tsx
  src/pages/change-requests/change-requests.test.tsx
  src/services/api-request.ts
  src/services/change-requests.ts
  src/services/projects.ts
  src/services/tests/api-request.test.ts
  src/services/tests/change-requests.test.ts
  src/services/tests/projects.test.ts
  src/services/tests/users.test.ts
  src/services/tests/work-packages.test.ts
  src/services/users.ts
  src/services/work-packages.ts
Labels: enhancement, front-end, new feature

#223 219- home page component
  src/app/app-authenticated/app-authenticated.test.tsx
  src/app/app-authenticated/app-authenticated.tsx
  src/app/app-main/app-main.test.tsx
  src/components/change-request-details/change-request-details.tsx
  src/components/project-details/project-details.tsx
  src/pages/home/home.module.css
  src/pages/home/home.test.tsx
  src/pages/home/home.tsx
Labels: enhancement, front-end

#226 Project - Update to Use React-Router Link
  src/app/app-authenticated/app-authenticated.test.tsx
  src/app/app-main/app-main.test.tsx
  src/components/nav-user-menu/nav-user-menu.test.tsx
  src/components/work-package-dependencies/work-package-dependencies.test.tsx
  src/components/work-package-dependencies/work-package-dependencies.tsx
  src/components/work-package-summary/work-package-summary.test.tsx
  src/components/work-package-summary/work-package-summary.tsx
  src/pages/change-request-details/change-request-details.test.tsx
  src/pages/change-requests/change-requests.test.tsx
  src/pages/home/home.test.tsx
  src/pages/login/login.test.tsx
  src/pages/wbs-details/wbs-details.test.tsx
  src/test-support/test-utils.tsx
Labels: back-end, improvement

#183 I138 leroy - adding 3 pipes
  src/shared/pipes.tsx
Labels: enhancement

#227 Enhance plain text login
  src/app/app-context/app-context.module.css
  src/app/app-context/app-context.test.tsx
  src/app/app-context/app-context.tsx
  src/app/app-core/app-core.module.css
  src/app/app-core/app-core.test.tsx
  src/app/app-core/app-core.tsx
  src/app/app-main/app-main.test.tsx
  src/app/app-main/app-main.tsx
  src/app/app-public/app-public.test.tsx
  src/app/app-public/app-public.tsx
  src/components/nav-user-menu/nav-user-menu.tsx
  src/pages/home/home.test.tsx
  src/pages/home/home.tsx
  src/pages/login/login.test.tsx
  src/pages/login/login.tsx
  src/setupTests.ts
  src/shared/routes.ts
Labels: enhancement, front-end, new feature

#228 Separate the projects-table container into a container
  src/components/projects-table/projects-table.css
  src/components/projects-table/projects-table.test.tsx
  src/components/projects-table/projects-table.tsx
  src/containers/projects-table/projects-table.test.tsx
  src/containers/projects-table/projects-table.tsx
Labels: front-end, improvement

#191 i163 - Creating project container
  src/containers/project-container/project-container.module.css
  src/containers/project-container/project-container.test.tsx
  src/containers/project-container/project-container.tsx
  src/pages/wbs-details/wbs-details.tsx
  src/services/projects.ts
  src/utils/src/validate-wbs.ts
  src/utils/tests/validate-wbs.test.ts
Labels: front-end, new feature

#230 #162 Created Work Package Container
  src/app/app-authenticated/app-authenticated.test.tsx
  src/app/app-public/app-public.test.tsx
  src/components/description-list/description-list.module.css
  src/components/description-list/description-list.tsx
  src/components/nav-notifications-menu/nav-notifications-menu.test.tsx
  src/components/nav-page-links/nav-page-links.test.tsx
  src/components/nav-top-bar/nav-top-bar.test.tsx
  src/components/projects-table/projects-table.module.css
  src/components/projects-table/projects-table.test.tsx
  src/components/work-package-summary/work-package-summary.test.tsx
  src/containers/project-container/project-container.test.tsx
  src/containers/work-package-container/work-package-container.module.css
  src/containers/work-package-container/work-package-container.test.tsx
  src/containers/work-package-container/work-package-container.tsx
  src/pages/projects/projects.test.tsx
  src/pages/projects/projects.tsx
  src/pages/wbs-details/wbs-details.test.tsx
  src/pages/wbs-details/wbs-details.tsx
  src/services/change-requests.ts
  src/services/projects.ts
  src/services/users.ts
  src/services/work-packages.ts
  src/shared/routes.ts
  src/utils/src/validate-wbs.ts
  src/utils/tests/validate-wbs.test.ts
Labels: enhancement, front-end, improvement, new feature
