Repository Northeastern-Electric-Racing/PM-Dashboard-v2, pull requests merged in 2021-04, with the labels that each got.

#127 i91 Logan - Create a Work Packages Summary Component
  src/components/work-package-summary/work-package-summary.module.css
  src/components/work-package-summary/work-package-summary.test.tsx
  src/components/work-package-summary/work-package-summary.tsx
  src/shared/pipes.tsx
  src/shared/tests/end-date-pipe.test.tsx
  src/shared/tests/list-pipe.test.tsx
Labels: front-end

#134 Added central frontend routes file
  src/shared/routes.ts
Labels: front-end, new feature

#133 Added central api routes file
  src/utils/src/api-routes.ts
  src/utils/src/index.ts
Labels: back-end, new feature

#106 i100 Front End - added new .ico file, updated index.html
  public/NERfavicon.ico
  public/NERfavicon192.png
  public/NERfavicon512.png
  public/index.html
  public/logo192.png
  public/logo512.png
  public/manifest.json
Labels: front-end, improvement

#143 Lifted the router up to index.tsx for authentication
  src/App.test.tsx
  src/App.tsx
  src/index.tsx
  src/pages/login/login.module.css
  src/pages/login/login.tsx
Labels: front-end, improvement

#144 Remove body tag and restyle 404 page
  src/pages/page-not-found/page-not-found.module.css
  src/pages/page-not-found/page-not-found.tsx
Labels: front-end, improvement

#145 Fix manufacturing spelling mistake
  src/utils/src/types/change-request-types.ts
Labels: bug, front-end

#146 Update Prisma to 2.19.0
  package-lock.json
  package.json
Labels: back-end

#132 Built API Route Matching, Integrated with projects endpoint
  package-lock.json
  src/backend/functions/projects.ts
  src/backend/tests/projects.test.ts
  src/backend/tests/users.test.ts
  src/utils/package-lock.json
  src/utils/package.json
  src/utils/src/api-utils.ts
  src/utils/src/dummy-data.ts
  src/utils/src/index.ts
  src/utils/src/types/api-utils-types.ts
  src/utils/tests/api-utils.test.ts
Labels: back-end, new feature

#153 Create Dummy Work Package Endpoint
  src/backend/functions/work-packages.ts
  src/backend/tests/work-packages.test.ts
  src/utils/src/dummy-data.ts
Labels: back-end, new feature

#147 Fix npm audit vulnerabiltity
  package-lock.json
Labels: improvement

#150 Add sections and database initialization section to Onboarding doc
  docs/Onboarding.md
Labels: documentation

#152 Add API_URL to utils and updated projects endpoint
  src/backend/functions/projects.ts
  src/backend/tests/projects.test.ts
  src/utils/src/api-routes.ts
Labels: back-end, bug

#161 #72 - Created Work Package Details Component
  src/components/work-package-details/work-package-details.module.css
  src/components/work-package-details/work-package-details.test.tsx
  src/components/work-package-details/work-package-details.tsx
Labels: front-end, new feature

#171 Add routeMatcher to users endpoint
  src/backend/functions/users.ts
  src/backend/tests/users.test.ts
  src/utils/src/api-routes.ts
Labels: back-end, enhancement

#168 Remove extra example and seed API endpoints
  src/backend/functions/example.ts
  src/backend/functions/seed.ts
  src/backend/tests/seed.test.ts
Labels: back-end, improvement

#166 Establish Database Seeding Process
  package-lock.json
  package.json
  src/backend/prisma/migrations/20210419064854_major_updates/migration.sql
  src/backend/prisma/migrations/migration_lock.toml
  src/backend/prisma/seed.ts
Labels: back-end, new feature

#107 #68 - Added Dummy API Endpoint for Change Requests
  src/backend/functions/change-requests.ts
  src/backend/tests/change-requests.test.ts
Labels: back-end, new feature

#173 Ensure incoming request paths have API path prefix
  src/utils/src/api-utils.ts
  src/utils/src/dummy-data.ts
  src/utils/tests/api-utils.test.ts
Labels: back-end, bug
