Repository Northeastern-Electric-Racing/PM-Dashboard-v2, pull requests merged in 2022-01, with the labels that each got.

#424 Standardize stage gate CR field name to confirmDone
  src/components/change-requests/change-request-details/change-request-details/change-request-details.test.tsx
  src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
  src/services/tests/change-requests.api.test.ts
  src/test-support/test-data/change-requests.stub.ts
  src/utils/src/types/change-request-types.ts
Labels: front-end

#425 Sort CR table desc
  src/components/change-requests/change-requests-table/change-requests-table/change-requests-table.tsx
Labels: front-end

#434 #391 - Separate Change Request Details Component
  src/components/change-requests/change-request-details/change-request-details/change-request-details.test.tsx
  src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
  src/components/change-requests/change-request-details/change-request-details/type-specific-details/activation-details/activation-details.module.css
  src/components/change-requests/change-request-details/change-request-details/type-specific-details/activation-details/activation-details.test.tsx
  src/components/change-requests/change-request-details/change-request-details/type-specific-details/activation-details/activation-details.tsx
  src/components/change-requests/change-request-details/change-request-details/type-specific-details/stage-gate-details/stage-gate-details.module.css
  src/components/change-requests/change-request-details/change-request-details/type-specific-details/stage-gate-details/stage-gate-details.test.tsx
  src/components/change-requests/change-request-details/change-request-details/type-specific-details/stage-gate-details/stage-gate-details.tsx
  src/components/change-requests/change-request-details/change-request-details/type-specific-details/standard-details/standard-details.module.css
  src/components/change-requests/change-request-details/change-request-details/type-specific-details/standard-details/standard-details.test.tsx
  src/components/change-requests/change-request-details/change-request-details/type-specific-details/standard-details/standard-details.tsx
Labels: front-end

#421 Populates Implemented Changes Section
  src/components/change-requests/change-request-details/change-request-details.test.tsx
  src/components/change-requests/change-request-details/change-request-details/change-request-details.test.tsx
  src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
  src/components/change-requests/change-request-details/change-request-details/implemented-changes-list/implemented-changes-list.module.css
  src/components/change-requests/change-request-details/change-request-details/implemented-changes-list/implemented-changes-list.test.tsx
  src/components/change-requests/change-request-details/change-request-details/implemented-changes-list/implemented-changes-list.tsx
  src/test-support/test-data/change-requests.stub.ts
Labels: front-end

#414 Create CR endpoint with Middy.js
  netlify.toml
  package-lock.json
  package.json
  src/backend/functions/change-requests-new.ts
  src/backend/tests/change-requests-new.test.ts
  src/test-support/test-data/test-utils.stub.ts
  src/utils/package-lock.json
  src/utils/src/api-routes.ts
  src/utils/tsconfig.json
Labels: back-end

#448 wire change request reviewing
  package-lock.json
  package.json
  src/backend/functions/change-requests-review.ts
  src/components/change-requests/review-change-request/review-change-request.tsx
  src/components/change-requests/review-change-request/review-change-request/review-change-request.tsx
  src/services/change-requests.api.ts
  src/services/change-requests.hooks.ts
  src/shared/urls.ts
  src/utils/package-lock.json
  src/utils/package.json
  src/utils/src/types/change-request-types.ts
Labels: front-end

#456 record cr reviewer
  src/backend/functions/change-requests-review.ts
  src/backend/functions/change-requests.ts
  src/backend/prisma/migrations/20220116033137_init/migration.sql
  src/backend/prisma/schema.prisma
  src/components/change-requests/change-request-details/change-request-details/change-request-details.tsx
  src/components/change-requests/change-request-details/change-request-details/review-notes/review-notes.test.tsx
  src/components/change-requests/change-request-details/change-request-details/review-notes/review-notes.tsx
  src/components/change-requests/review-change-request/review-change-request.tsx
  src/services/change-requests.api.ts
  src/services/change-requests.hooks.ts
  src/test-support/test-data/change-requests.stub.ts
  src/utils/src/types/change-request-types.ts
Labels: front-end, back-end

#460 cr table no
  src/backend/prisma/seed-data/change-requests.ts
  src/components/change-requests/change-requests-table/change-requests-table.tsx
  src/components/change-requests/change-requests-table/change-requests-table/change-requests-table.tsx
Labels: front-end

#462 #321 - When to push package.json?
  docs/ContributorGuide.md
Labels: documentation

#490 #443 - Status Setting Bug
  src/components/projects/projects-table/projects-table-filter/projects-table-filter.test.tsx
  src/components/projects/projects-table/projects-table-filter/projects-table-filter.tsx
Labels: bug, front-end
